# Generated by Django 2.1.7 on 2020-10-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user_flag',
            field=models.SmallIntegerField(default=1),
        ),
    ]
