# Generated by Django 2.1.7 on 2020-10-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_flag',
            field=models.SmallIntegerField(default=1),
        ),
    ]
